### ISSUE TITLE
AWS Best Practice for Security

### ISSUE THREAD

**Issue by Nighteyez07** [tferrari92/automate-all-the-things#3]
Within the README there is a section for **Get your AWS keys**. In this section the steps call out getting the access keys for the user. Even a user not running as Root probably has more access than they should. Try to follow the Least Privilege Access model where you can.
- Create a new user just for the service connection
- Create a custom policy for the user, this policy will control the types of resources and/or resources that the user can work against
- Finally, recommend turning that policy into IaC itself so you can easily replicate it as part of your Automate Everything (here's a link to the Terraform documentation on AWS IAM policies - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy)

Once you've done that, you'll want to update the README on the Service Connection as well to reference the new user.

**Comment by tferrari92** [comment]
Hey! Thank you for taking the time!

Yes, this is definitely not a good security practice.

The project is mainly aimed at a beginner who is just setting up his first DevOps lab, so keeping it simple is one of the top priorities. I need to think of a way to accommodate for this without making it more complex or confusing for this type of user.

To fix this, there's tasks that must be done before running any pipeline, so I would not be able to automate these tasks away from the user. I think for this Regular Edition I'll keep it as is, and probably add this in a follow-up edition where the target user is expected to be more knowledgeable.

Thank you 🙏!

**Comment by sstaley-hioscar** [comment]
Also consider assuming a role instead of creating a service user. Service users require credentials, which can stick around way longer than intended, and may not be rotated as often as necessary. Instead, you can use OIDC to assume a role from a non-aws system (at least, it's available via github actions. Not sure if it's available via azure devops). If your automation is running on AWS it will be able to assume the role natively. You'll need to set the role's assume role policy up to allow it to be assumed by whatever system is running the automation.
